import { test, expect, type Page } from "@playwright/test";
import { seedNetwork } from "../../mocks/fixtures";
test.skip(process.env.GONGZHI_TEST_AUTH !== "1", "Only run against the explicit localhost dummy-Auth test build.");
async function localIdentity(page: Page) {
  const n = seedNetwork(); n.graph.nodes = n.needs.map(need => ({ id: need.id, label: need.title, type: "need", mode: "demo" }));
  const data = JSON.parse(JSON.stringify(n).replaceAll('"mode":"demo"', '"mode":"live"'));
  await page.route("**/api/gongzhi/network", route => route.fulfill({ json: { ok: true, mode: "live", data } }));
  await page.route("**/api/gongzhi/owners", route => route.fulfill({ json: { ok: true, mode: "live", data: [data.owners[0]] } }));
  await page.route("**/test-auth/auth/v1/token?grant_type=password", route => route.fulfill({ json: { access_token: "local-ui-test-access", refresh_token: "local-ui-test-refresh", token_type: "bearer", expires_in: 3600, user: { id: "11111111-1111-4111-8111-111111111111", aud: "authenticated", role: "authenticated", email: "test@localhost.invalid", created_at: "2026-09-13T00:00:00.000Z" } } }));
  await page.goto("/network/"); await page.getByRole("button", { name: "登录", exact: true }).click(); await page.getByLabel("公开显示名称").fill("本机测试身份"); await page.getByLabel("邮箱", { exact: true }).fill("test@localhost.invalid"); await page.getByLabel("密码", { exact: true }).fill("local-ui-test-password"); await page.getByRole("button", { name: "登录并建立发布身份" }).click(); await expect(page.getByRole("button", { name: "退出登录" })).toBeVisible(); await page.getByTestId("record-story-b").click();
}
const run = { id: "local-test-run", need_id: "story-b", need_revision: 1, owner_id: "local-platform-owner", status: "queued", idempotency_key: "", deadline_at: "2026-09-13T13:40:00.000Z", created_at: "2026-09-13T13:39:00.000Z", updated_at: "2026-09-13T13:39:00.000Z", result_id: null, error: null, usage: { model_steps: 0, zhihu_queries: 0, input_tokens: null, output_tokens: null }, mode: "live" };
test("助手 UI 仅等到真实形状回执才显示运行；失败重试同 key，已有 run 可查询取消", async ({ page }) => {
  const keys: string[] = []; let release: (() => void) | undefined;
  await page.route("**/api/gongzhi/runs", async route => { const body = route.request().postDataJSON(); keys.push(body.idempotency_key); if (keys.length === 1) return route.fulfill({ status: 503, json: { ok: false, mode: "live", error: { code: "unavailable", message: "本机测试：助手暂不可用", retryable: true } } }); await new Promise<void>(resolve => { release = resolve; }); await route.fulfill({ json: { ok: true, mode: "live", data: { ...run, idempotency_key: body.idempotency_key } } }); });
  await page.route("**/api/gongzhi/runs/local-test-run", route => route.fulfill({ json: { ok: true, mode: "live", data: { ...run, status: route.request().method() === "DELETE" ? "cancelled" : "running", idempotency_key: keys[0] } } }));
  await localIdentity(page); await page.getByRole("button", { name: "请平台体验助手帮忙" }).click(); await expect(page.getByRole("alert")).toContainText("本机测试：助手暂不可用"); await page.getByRole("button", { name: "用同一次请求重试" }).click(); await expect(page.getByText("正在等待服务响应；收到回执前不确认已开始或完成执行。", { exact: true })).toBeVisible(); await expect(page.getByText("服务已确认：正在处理", { exact: true })).toHaveCount(0); expect(keys).toHaveLength(2); expect(keys[0]).toBe(keys[1]); release!(); await expect(page.getByText("服务已确认：排队中", { exact: true })).toBeVisible(); await page.getByRole("button", { name: "查看已有请求状态" }).click(); await expect(page.getByText("服务已确认：正在处理", { exact: true })).toBeVisible(); await page.getByRole("button", { name: "取消这次帮助" }).click(); await expect(page.getByText("这次帮助已取消", { exact: true })).toBeVisible(); await expect(page.getByRole("button", { name: "请平台体验助手帮忙" })).toHaveCount(0);
});
test("真实形状的 Agent 绑定凭据只显示一次，不写浏览器存储", async ({ page }) => {
  await localIdentity(page); await page.getByRole("button", { name: "关闭面板", exact: true }).click();
  const human = { ...seedNetwork().owners[0], mode: "live" }, agent = { ...seedNetwork().owners[1], id: "local-owned-agent", name: "本机凭据测试助手", mode: "live" };
  await page.route("**/api/gongzhi/owners", route => route.fulfill({ json: { ok: true, mode: "live", data: route.request().method() === "POST" ? { owner: agent, api_key: "local-dummy-agent-once" } : [human, agent] } }));
  await page.getByRole("button", { name: "接入我的 Agent", exact: true }).click(); await page.getByLabel("Agent 名称").fill(agent.name); await page.getByRole("button", { name: "绑定我的 Agent", exact: true }).click(); await expect(page.getByText("local-dummy-agent-once", { exact: true })).toBeVisible(); expect(await page.evaluate(() => JSON.stringify({ ...localStorage, ...sessionStorage }).includes("local-dummy-agent-once"))).toBe(false); await page.getByRole("button", { name: "关闭面板", exact: true }).click(); await page.getByRole("button", { name: "接入我的 Agent", exact: true }).click(); await expect(page.getByText("local-dummy-agent-once", { exact: true })).toHaveCount(0); await expect(page.getByText(agent.name, { exact: true })).toBeVisible();
});
