import { test, expect, type Page } from "@playwright/test";
import { mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { seedNetwork, storyResult } from "../../mocks/fixtures";
const evidence = path.join(tmpdir(), "gongzhi-frontend-evidence");
async function demo(page: Page) { await page.goto("/demo/"); await expect(page.getByTestId("record-story-a")).toBeVisible(); }
async function close(page: Page) { await page.getByRole("button", { name: "关闭面板", exact: true }).click(); }
test("首片：桌面三入口、三故事与截图", async ({ page }) => {
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message));
  await mkdir(evidence, { recursive: true }); await page.goto("/"); await expect(page.getByRole("heading", { name: /一个人的难题，\s*也许是另一颗星的光。/ })).toBeVisible();
  await page.screenshot({ path: path.join(evidence, "landing-desktop.png"), fullPage: true });
  await page.getByRole("link", { name: "探索示例星群" }).click(); await expect(page.getByTestId("record-story-a")).toBeVisible();
  await expect(page.getByRole("button", { name: "放大星图" })).toBeEnabled();
  await page.screenshot({ path: path.join(evidence, "space-desktop.png"), fullPage: true });
  await page.getByRole("button", { name: "接入我的 Agent", exact: true }).click(); await page.getByLabel("Agent 名称").fill("我的示例助手"); await page.getByLabel("它能提供哪些帮助？").fill("活动策划，信息整理"); await page.getByRole("button", { name: "建立示例绑定" }).click(); await expect(page.getByText("示例绑定已保存；没有真实连接。")).toBeVisible(); await expect(page.getByText("尚无在线活动记录", { exact: true })).toBeVisible(); await close(page);
  await page.getByRole("button", { name: "发布需求", exact: true }).click(); await page.getByLabel("想完成什么？").fill("新的输入不会假装获得模型回答"); await page.getByLabel("目前遇到了什么困难？").fill("希望组织一场新的 AI 活动，使用不同人数与条件。"); await page.getByLabel("我确认").check(); await page.getByRole("dialog").getByRole("button", { name: "发布需求", exact: true }).click(); await expect(page.getByRole("heading", { name: "新的输入不会假装获得模型回答" })).toBeVisible(); await expect(page.getByText("暂时还没有回应", { exact: true })).toBeVisible(); await expect(page.getByRole("button", { name: "查看示例帮助" })).toHaveCount(0); await close(page);
  await page.getByRole("button", { name: "分享经验", exact: true }).click(); await page.getByLabel("给这个方法起个名字").fill("我的独立方法"); await page.getByLabel("具体步骤与经验").fill("先确认目标，再留下复盘。"); await page.getByLabel("我确认").check(); await page.getByRole("dialog").getByRole("button", { name: "分享经验", exact: true }).click(); await expect(page.getByRole("heading", { name: "我的独立方法" })).toBeVisible(); await expect(page.getByText(/作者经验 · 没有提供外部来源/)).toBeVisible(); await close(page);
  await page.getByTestId("record-story-a").click(); await page.getByRole("button", { name: "查看示例帮助" }).click(); await expect(page.getByRole("heading", { name: "90 分钟，让每个人带走一张自己的作品" })).toBeVisible(); await page.getByRole("button", { name: "采纳这份结果" }).click(); await expect(page.getByText("人类已采纳", { exact: true })).toBeVisible(); await page.screenshot({ path: path.join(evidence, "story-a-accepted.png"), fullPage: true }); await close(page);
  await page.getByTestId("record-story-b").click(); await expect(page.getByText("暂时还没有回应", { exact: true })).toBeVisible(); await expect(page.getByRole("button", { name: "查看示例帮助" })).toHaveCount(0); await close(page);
  await page.getByTestId("record-story-c").click(); await page.getByRole("button", { name: "查看示例帮助" }).click(); await page.getByRole("button", { name: "先做一张共识卡，再开始分工 · v1" }).click(); await expect(page.getByText(/保存，是留作参考；引用/)).toBeVisible(); await expect(page.getByRole("button", { name: "用共识卡 v1 组织一次读书会复盘" })).toBeVisible();
  expect(errors).toEqual([]);
});
test("首片：窄屏三个入口与减弱动态", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await page.emulateMedia({ reducedMotion: "reduce" }); await page.goto("/"); await expect(page.getByRole("button", { name: "动态已减弱" })).toBeVisible(); await page.screenshot({ path: path.join(evidence, "landing-mobile.png"), fullPage: true });
  await demo(page); await expect(page.getByRole("button", { name: "放大星图" })).toBeEnabled(); await page.screenshot({ path: path.join(evidence, "space-mobile.png"), fullPage: true });
  for (const name of ["接入我的 Agent", "发布需求", "分享经验"]) { await page.getByRole("button", { name, exact: true }).click(); await expect(page.getByRole("dialog")).toBeVisible(); await close(page); }
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
test("浏览器刷新恢复草稿与记录，重置只清示例，跨模式没有控制权或假数据", async ({ page }) => {
  const liveRequests: string[] = []; page.on("request", req => { if (req.url().includes("/api/gongzhi/")) liveRequests.push(req.url()); });
  await demo(page); await page.evaluate(() => { localStorage.setItem("gongzhi.live.draft.visitor.need.new", JSON.stringify({ title: "真实草稿保持独立" })); localStorage.setItem("gongzhi.live.auth.v1", "test-sentinel-not-a-token"); });
  await page.getByRole("button", { name: "发布需求", exact: true }).click(); await page.getByLabel("想完成什么？").fill("刷新恢复的示例草稿"); await close(page); await page.reload(); await expect(page.getByTestId("record-story-a")).toBeVisible(); await page.getByRole("button", { name: "发布需求", exact: true }).click(); await expect(page.getByLabel("想完成什么？")).toHaveValue("刷新恢复的示例草稿"); await page.getByLabel("目前遇到了什么困难？").fill("仅用本机示例保存。"); await page.getByLabel("我确认").check(); await page.getByRole("dialog").getByRole("button", { name: "发布需求", exact: true }).click(); await expect(page.getByRole("heading", { name: "刷新恢复的示例草稿" })).toBeVisible(); await close(page); await page.reload(); await expect(page.getByRole("button", { name: /刷新恢复的示例草稿/ })).toBeVisible();
  const scopes = await page.evaluate(async () => (await navigator.serviceWorker.getRegistrations()).map(r => new URL(r.scope).pathname)); expect(scopes).toEqual(["/demo/"]);
  const rejected = await page.evaluate(async () => { const response = await fetch("/demo/api/unknown", { method: "POST" }); return { status: response.status, body: await response.json() }; }); expect(rejected.status).toBe(503); expect(rejected.body.mode).toBe("demo"); expect(liveRequests).toEqual([]);
  await page.getByRole("button", { name: "重置示例", exact: true }).click(); await page.getByRole("button", { name: "确认重置示例" }).click(); await expect(page.getByRole("button", { name: /刷新恢复的示例草稿/ })).toHaveCount(0); expect(await page.evaluate(() => localStorage.getItem("gongzhi.live.auth.v1"))).toBe("test-sentinel-not-a-token");
  await page.getByRole("link", { name: "进入真实空间" }).click(); await expect(page.getByRole("heading", { name: "真实空间暂时未能连接" })).toBeVisible(); expect(await page.evaluate(() => navigator.serviceWorker.controller)).toBeNull(); await expect(page.getByTestId("record-story-a")).toHaveCount(0); await page.getByRole("button", { name: "发布需求", exact: true }).click(); await expect(page.getByLabel("想完成什么？")).toHaveValue("真实草稿保持独立"); await expect(page.getByRole("dialog").getByRole("button", { name: "发布需求", exact: true })).toBeDisabled(); await close(page); await page.getByRole("button", { name: "登录", exact: true }).click(); await expect(page.getByRole("button", { name: "登录并建立发布身份" })).toBeDisabled(); await expect(page.getByLabel(/token|令牌/i)).toHaveCount(0);
});
test("窄屏完成三故事、需求修改撤回与 Agent 撤销", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await demo(page);
  await page.getByTestId("record-story-a").click(); await page.getByRole("button", { name: "查看示例帮助" }).click(); await page.getByRole("button", { name: "请补充说明" }).click(); await expect(page.getByText("请求补充", { exact: true })).toBeVisible(); await page.getByRole("button", { name: "采纳这份结果" }).click(); await expect(page.getByText("人类已采纳", { exact: true })).toBeVisible(); await close(page);
  await page.getByTestId("record-story-b").click(); await page.getByRole("button", { name: "修改需求", exact: true }).click(); await page.getByLabel("有哪些限制？").fill("不能通电或拆卸；补充了限制。"); await page.getByLabel("我确认").check(); await page.getByRole("button", { name: "保存修改", exact: true }).click(); await expect(page.getByText("需求 v2 · 示例", { exact: true })).toBeVisible(); await expect(page.getByText("暂时还没有回应", { exact: true })).toBeVisible(); await page.getByRole("button", { name: "撤回需求", exact: true }).click(); await page.getByRole("button", { name: "确认撤回", exact: true }).click(); await expect(page.getByRole("dialog").getByText("已撤回", { exact: true })).toBeVisible(); await close(page);
  await page.getByTestId("record-story-c").click(); await page.getByRole("button", { name: "查看示例帮助" }).click(); await page.getByRole("button", { name: "先做一张共识卡，再开始分工 · v1" }).click(); await page.getByRole("button", { name: "保存到本机", exact: true }).click(); await expect(page.getByRole("button", { name: "已保存到本机", exact: true })).toBeVisible(); await close(page);
  await page.getByRole("button", { name: "接入我的 Agent", exact: true }).click(); await page.getByLabel("Agent 名称").fill("窄屏助手"); await page.getByRole("button", { name: "建立示例绑定" }).click(); await page.getByRole("button", { name: "撤销绑定", exact: true }).click(); await page.getByRole("button", { name: "确认撤销", exact: true }).click(); await expect(page.getByText("已撤销 · 历史记录保留", { exact: true })).toBeVisible();
});
test("浏览器旧版采纳、来源安全、图关闭后列表与搜索仍完整可用", async ({ page }) => {
  await demo(page); await page.getByTestId("record-story-a").click(); await page.getByRole("button", { name: "查看示例帮助" }).click(); await page.getByRole("button", { name: "修改需求", exact: true }).click(); await page.getByLabel("想完成什么？").fill("活动新版本，换了参与条件"); await page.getByLabel("我确认").check(); await page.getByRole("button", { name: "保存修改", exact: true }).click(); await expect(page.getByText("这是旧版需求的结果，不能被当前 v2 采纳。", { exact: true })).toBeVisible(); await expect(page.getByRole("button", { name: "采纳这份结果" })).toHaveCount(0); await close(page);
  await page.getByRole("button", { name: "仅看列表", exact: true }).click(); await expect(page.getByTestId("network-canvas")).toHaveCount(0); await page.getByLabel("搜索星群").fill("小众问题"); await expect(page.getByTestId("record-story-b")).toBeVisible(); await expect(page.getByTestId("record-story-a")).toHaveCount(0); await page.getByTestId("record-story-b").click(); await expect(page.getByRole("heading", { name: "寻找能修复老式星图仪的人" })).toBeVisible(); await close(page);
  await page.getByRole("button", { name: "分享经验", exact: true }).click(); await page.getByLabel("给这个方法起个名字").fill("带来源的经验"); await page.getByLabel("具体步骤与经验").fill("<script>window.unsafeExecuted=true</script> 不会执行不可信 HTML。"); await page.getByText("添加来源（可选）", { exact: true }).click(); await page.getByLabel("来源链接", { exact: true }).fill("javascript:alert(1)"); await page.getByLabel("我确认").check(); await page.getByRole("dialog").getByRole("button", { name: "分享经验", exact: true }).click(); await expect(page.getByRole("alert")).toContainText("来源链接只支持"); await page.getByLabel("来源链接", { exact: true }).fill("https://example.com/reference"); await page.getByLabel("来源作者", { exact: true }).fill("资料作者"); await page.getByRole("dialog").getByRole("button", { name: "分享经验", exact: true }).click(); await expect(page.getByRole("link", { name: "查看来源" })).toHaveAttribute("href", "https://example.com/reference"); await expect(page.getByText("引用资料 · 未取回全文", { exact: true })).toBeVisible(); expect(await page.evaluate(() => Reflect.get(window, "unsafeExecuted"))).toBeUndefined();
});
test("Cosmos 实际星点选择、连续缩放和平移；选择映射至相同记录", async ({ page }) => {
  await demo(page); await expect(page.getByRole("button", { name: "放大星图" })).toBeEnabled();
  const star = page.locator('.graph-node-label[data-node-id="story-a"]'); await expect(star).toBeVisible();
  const point = () => star.evaluate(el => { const parent = el.parentElement!.getBoundingClientRect(), style = (el as HTMLElement).style; return { x: parent.x + parseFloat(style.left), y: parent.y + parseFloat(style.top) }; });
  const first = await point(); await page.getByRole("button", { name: "放大星图" }).click(); const enlarged = await point(); await page.getByRole("button", { name: "放大星图" }).click(); const twice = await point(); expect(enlarged).not.toEqual(first); expect(twice).not.toEqual(enlarged); await page.getByRole("button", { name: "缩小星图" }).click(); await page.getByRole("button", { name: "显示全部星点" }).click();
  const canvas = page.locator(".cosmos-host canvas"), box = await canvas.boundingBox(); expect(box).not.toBeNull();
  const beforePan = await point(); await page.mouse.move(box!.x + 100, box!.y + 120); await page.mouse.down(); await page.mouse.move(box!.x + 135, box!.y + 145, { steps: 8 }); await page.mouse.up(); const afterPan = await point(); expect(afterPan).not.toEqual(beforePan);
  await page.mouse.move(afterPan.x, afterPan.y); await expect(page.locator(".graph-tooltip")).toContainText("第一次办 AI 体验活动"); await page.mouse.click(afterPan.x, afterPan.y); await expect(page.getByRole("dialog").getByRole("heading", { name: "第一次办 AI 体验活动，怎样让新手玩起来？" })).toBeVisible();
});
test("强制 WebGL 不可用时明确降级，完整列表仍能发需求", async ({ page }) => {
  await page.addInitScript(() => { const original = HTMLCanvasElement.prototype.getContext; HTMLCanvasElement.prototype.getContext = function(this: HTMLCanvasElement, kind: string, ...args: unknown[]) { if (kind === "webgl2" || kind === "webgl" || kind === "experimental-webgl") return null; return Reflect.apply(original, this, [kind, ...args]); } as typeof original; });
  await demo(page); await expect(page.getByText("当前设备无法打开星图", { exact: true })).toBeVisible(); await expect(page.getByRole("button", { name: "放大星图" })).toBeDisabled(); await page.getByTestId("record-story-b").click(); await expect(page.getByText("暂时还没有回应", { exact: true })).toBeVisible(); await close(page); await page.getByRole("button", { name: "发布需求", exact: true }).click(); await page.getByLabel("想完成什么？").fill("图形失败也能发布"); await page.getByLabel("目前遇到了什么困难？").fill("使用完整列表完成公开示例操作。"); await page.getByLabel("我确认").check(); await page.getByRole("dialog").getByRole("button", { name: "发布需求", exact: true }).click(); await expect(page.getByRole("heading", { name: "图形失败也能发布" })).toBeVisible();
});
test("提交已接受但响应丢失后原草稿安全重试，双击不会重复创建", async ({ page }) => {
  await demo(page); await page.evaluate(() => { const original = window.fetch; let drop = true; window.fetch = async (...args) => { const response = await original(...args); if (String(args[0]).includes("/demo/api/experiences") && args[1]?.method === "POST" && drop) { drop = false; throw new TypeError("simulated response loss after acceptance"); } return response; }; });
  // createApiClient captures fetch at boot, so wrap before a fresh document's client creation.
  await page.addInitScript(() => { const original = window.fetch; let drop = true; window.fetch = async (...args) => { const response = await original(...args); if (String(args[0]).includes("/demo/api/experiences") && args[1]?.method === "POST" && drop) { drop = false; throw new TypeError("simulated response loss after acceptance"); } return response; }; });
  await page.reload(); await expect(page.getByTestId("record-story-a")).toBeVisible(); await page.getByRole("button", { name: "分享经验", exact: true }).click(); await page.getByLabel("给这个方法起个名字").fill("可重试的来源经验"); await page.getByLabel("具体步骤与经验").fill("响应丢失不需要改写原来的来源日期。"); await page.getByText("添加来源（可选）", { exact: true }).click(); await page.getByLabel("来源链接", { exact: true }).fill("https://example.com/stable"); await page.getByLabel("我确认").check(); await page.getByRole("dialog").getByRole("button", { name: "分享经验", exact: true }).click(); await expect(page.getByRole("alert")).toContainText("无法连接服务"); await expect(page.getByLabel("给这个方法起个名字")).toHaveValue("可重试的来源经验"); await page.getByRole("dialog").getByRole("button", { name: "分享经验", exact: true }).dblclick(); await expect(page.getByRole("heading", { name: "可重试的来源经验" })).toBeVisible(); const count = await page.evaluate(async () => { const json = await (await fetch("/demo/api/network")).json(); return json.data.experiences.filter((e: { title: string }) => e.title === "可重试的来源经验").length; }); expect(count).toBe(1);
});
test("图的实际引用连线可打开依据，列表详情也能追溯同一记录", async ({ page }) => {
  await demo(page); await page.getByTestId("record-story-c").click(); await page.getByRole("button", { name: "查看示例帮助" }).click(); await close(page); await expect(page.locator('.graph-node-label[data-node-id="result-F-C"]')).toBeVisible();
  const point = (id: string) => page.locator(`.graph-node-label[data-node-id="${id}"]`).evaluate(el => { const parent = el.parentElement!.getBoundingClientRect(), style = (el as HTMLElement).style; return { x: parent.x + parseFloat(style.left), y: parent.y + parseFloat(style.top) }; });
  const source = await point("result-F-C"), target = await point("experience-c-v1"); await page.mouse.move((source.x + target.x) / 2, (source.y + target.y) / 2); await expect(page.locator(".graph-tooltip")).toContainText("版本引用"); await page.mouse.click((source.x + target.x) / 2, (source.y + target.y) / 2); await expect(page.getByRole("dialog").getByRole("heading", { name: "用共识卡 v1 组织一次读书会复盘" })).toBeVisible(); await close(page);
  await page.getByRole("button", { name: "仅看列表", exact: true }).click(); await page.getByTestId("record-experience-c-v1").click(); await page.getByRole("button", { name: "版本引用 · 查看依据" }).click(); await expect(page.getByRole("dialog").getByRole("heading", { name: "用共识卡 v1 组织一次读书会复盘" })).toBeVisible();
});
test("匿名真实公开界面禁用助手，引用不在星图快照中仍读取精确版本", async ({ page }) => {
  // Test-only HTTP responses exercise read-only live UI; these are not real service evidence.
  const n = seedNetwork(), exact = n.experiences[0]; n.results.push({ ...storyResult("F-C")!, id: "result-F-C", created_at: "2026-09-13T02:00:00.000Z" }); n.experiences = []; n.graph.nodes = n.needs.map(need => ({ id: need.id, label: need.title, type: "need", mode: "demo" }));
  const data = JSON.parse(JSON.stringify(n).replaceAll('"mode":"demo"', '"mode":"live"')); let versionReads = 0;
  await page.route("**/api/gongzhi/network", route => route.fulfill({ json: { ok: true, mode: "live", data } })); await page.route("**/api/gongzhi/experiences/experience-c-v1", route => { versionReads++; return route.fulfill({ json: { ok: true, mode: "live", data: { ...exact, mode: "live" } } }); });
  await page.goto("/network/"); await page.getByTestId("record-story-c").click(); await expect(page.getByRole("button", { name: "请平台体验助手帮忙" })).toBeDisabled(); await page.getByRole("button", { name: "查看对应经验 · v1" }).click(); await expect(page.getByRole("heading", { name: exact.title })).toBeVisible(); expect(versionReads).toBe(1);
});
