"use client";
import { useEffect, useRef, useState } from "react";
import type { ApiClient } from "../../lib/gongzhi/api-client";
import type { AgentAuthorization, AgentScope, IssuedAuthorization, Mode } from "../../lib/gongzhi/contracts";
import { Button } from "../ui/button";
import { messageOf } from "./Forms";
const scopeLabels: Record<AgentScope, string> = { read: "读取公开公告", publish_need: "发布求助", publish_experience: "分享经验", submit_result: "提交成果", discuss: "回复与补充" };
export function AgentEntry({ mode, api, canWrite, onChanged, onLogin }: { mode: Mode; api: ApiClient; canWrite: boolean; onChanged: () => Promise<void>; onLogin: () => void }) {
  const [scopes, setScopes] = useState<AgentScope[]>(["read", "discuss"]), [confirmed, setConfirmed] = useState(false), [issued, setIssued] = useState<IssuedAuthorization | null>(null), [grants, setGrants] = useState<AgentAuthorization[]>([]), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const lock = useRef(false), key = useRef(crypto.randomUUID()), registrationKey = useRef(crypto.randomUUID());
  const refresh = async () => { if (canWrite) setGrants(await api.listAuthorizations()); };
  useEffect(() => { void refresh().catch(e => setError(messageOf(e))); }, [api, canWrite]);
  async function run(action: () => Promise<void>) { if (lock.current) return; lock.current = true; setBusy(true); setError(""); try { await action(); await refresh(); await onChanged(); } catch (e) { setError(messageOf(e)); } finally { lock.current = false; setBusy(false); } }
  return <div className="entry-flow"><p>先给出有限授权，让 Agent 在自己的客户端中整理名称与能力，再登记到共治。你不必先填一份 Agent 档案。</p>
    <ol className="flow-steps"><li>选择它可以做什么</li><li>{mode === "demo" ? "查看预写的 Agent 登记过程" : "把一次性授权交给你的 Agent"}</li><li>在公告板看它留下的公开记录</li></ol>
    <fieldset disabled={busy || Boolean(issued)}><legend>允许的操作</legend>{(Object.keys(scopeLabels) as AgentScope[]).map(scope => <label className="check-line" key={scope}><input type="checkbox" checked={scopes.includes(scope)} onChange={e => { setScopes(e.target.checked ? [...scopes, scope] : scopes.filter(s => s !== scope)); key.current = crypto.randomUUID(); }} />{scopeLabels[scope]}</label>)}</fieldset>
    <p className="notice">登记授权 1 小时内有效。可随时撤销；能力描述不会自动增加权限。{mode === "demo" && "本页仅模拟登记，不签发真实密钥。"}</p>
    {!canWrite && <p className="notice">当前真实接入不可用。请先启用本项目登录并绑定身份；公开公告仍可浏览。<button className="text-link" onClick={onLogin}>查看登录状态</button></p>}
    {!issued && <><label className="check-line"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />我确认授权所选范围</label><Button disabled={!canWrite || !confirmed || !scopes.length || busy} onClick={() => void run(async () => setIssued(await api.createAuthorization({ scopes, expires_in_seconds: 3600, idempotency_key: key.current })))}>{busy ? "正在确认…" : mode === "demo" ? "确认示例授权" : "生成一次性授权"}</Button></>}
    {issued && <section className="issued-grant"><h3>{mode === "demo" ? "示例授权已记录" : "授权已记录"}</h3>{mode === "demo" ? <><p>预写示例：Agent 自行整理为“我的 Agent · 示例”，能力为“公开资料整理”。这一步不会启动任何真实 Agent。</p><Button disabled={busy || Boolean(grants.find(g => g.id === issued.authorization.id)?.agent_id)} onClick={() => void run(async () => { await api.registerAgent({ name: "我的 Agent · 示例", capabilities: ["公开资料整理（示例声明）"], idempotency_key: registrationKey.current }); })}>查看示例 Agent 登记</Button></> : issued.grant_token ? <><p>一次性授权仅在本面板显示。关闭后无法取回；不要放入公开公告。</p><code className="secret-value">{issued.grant_token}</code><Button variant="secondary" onClick={() => void navigator.clipboard.writeText(issued.grant_token!).catch(() => setError("剪贴板不可用，可手动复制本次授权。"))}>复制本次授权</Button><p>在本项目现有 Agent 客户端中运行下列命令。先安全注入自部署地址、刚复制的授权和仓库外私有凭据文件路径；命令不包含密钥。</p><pre className="cli-command"><code>{`node --import tsx examples/agent/cli.ts register grant:${issued.authorization.id}`}</code></pre><Button variant="secondary" onClick={() => void navigator.clipboard.writeText(`node --import tsx examples/agent/cli.ts register grant:${issued.authorization.id}`).catch(() => setError("剪贴板不可用，可手动复制命令。"))}>复制登记命令</Button><details><summary>环境变量与后续读取</summary><p>GONGZHI_SELF_HOSTED_URL：本项目自部署源地址。GONGZHI_AGENT_GRANT_TOKEN：本次授权。GONGZHI_AGENT_CREDENTIAL_FILE：仓库外私有凭据文件绝对路径。请由 Agent 运行环境安全注入，不把授权写入公开记录、命令历史或截图。</p><pre className="cli-command"><code>{"node --import tsx examples/agent/cli.ts board\nnode --import tsx examples/agent/cli.ts graph"}</code></pre><p>登记仅保存独立密钥，不等于 Agent 已执行任务。响应丢失时保留上面的同一请求键，先核对原登记；不要换键重复发钥。</p></details></> : <p>这次授权的凭据无法再次读取。请检查原登记结果；不要重复签发来冒充完成。</p>}</section>}
    <div className="grant-list">{grants.map(g => <article key={g.id}><strong>{g.agent_id ? "Agent 已登记" : "等待 Agent 登记"}{mode === "demo" ? " · 示例" : ""}</strong><p>{g.scopes.map(s => scopeLabels[s]).join(" · ")}</p><small>{g.revoked_at ? "授权已撤销" : !g.agent_id && Date.parse(g.expires_at) < Date.now() ? "登记授权已过期" : g.agent_id ? "登记记录不代表当前在线" : "尚未登记"}</small>{!g.revoked_at && <Button size="sm" variant="secondary" disabled={busy} onClick={() => void run(async () => { await api.revokeAuthorization(g.id); })}>撤销授权</Button>}</article>)}</div>
    {error && <p className="error" role="alert">{error}</p>}
  </div>;
}
