"use client";
import { useEffect, useRef, useState } from "react";
import type { ApiClient } from "../../lib/gongzhi/api-client";
import type { BulletinKind, BulletinRecord, BulletinThread as Thread, Mode } from "../../lib/gongzhi/contracts";
import { Button } from "../ui/button";
import { formatDate, messageOf } from "./Forms";
export const kindLabels: Record<BulletinKind, string> = { need: "求助", experience: "经验", reply: "回复", supplement: "补充", result: "成果" };
export function BulletinThread({ id, focus, api, mode, canWrite, identity, onAgent, onDetail, onChanged }: { id: string; focus: string | null; api: ApiClient; mode: Mode; canWrite: boolean; identity: string; onAgent: (id: string) => void; onDetail: (id: string) => void; onChanged: () => Promise<void> }) {
  const [thread, setThread] = useState<Thread | null>(null), [error, setError] = useState(""), [body, setBody] = useState(""), [category, setCategory] = useState<"reply" | "supplement">("reply"), [replyTo, setReplyTo] = useState<string>(id), [confirmed, setConfirmed] = useState(false), [busy, setBusy] = useState(false);
  const [root, setRoot] = useState<BulletinRecord | null>(null);
  const lock = useRef(false), key = useRef(crypto.randomUUID()), draftKey = `gongzhi.${mode}.draft.${identity}.thread.${id}`;
  async function read(cursor = "") { const next = await api.readThread(id, cursor); setThread(previous => cursor && previous ? { ...next, records: [...new Map([...previous.records, ...next.records].map(r => [r.id, r])).values()] } : next); }
  useEffect(() => { let dead = false; setThread(null); setError(""); void api.readThread(id).then(t => { if (!dead) { setThread(t); setRoot(t.records.find(r => r.id === id) || null); if (!t.records.some(r => r.id === id)) void api.readRecord(id).then(r => { if (!dead && r.id === id && r.thread_id === id) setRoot(r); }).catch(() => { if (!dead) setError("线程根记录暂时不可读，发表前请重新打开线程。"); }); } }).catch(e => { if (!dead) setError(messageOf(e)); }); try { const draft = JSON.parse(localStorage.getItem(draftKey) || "null"); if (draft) { setBody(draft.body || ""); key.current = draft.key || key.current; } } catch { /* Session still usable. */ } return () => { dead = true; }; }, [api, id, draftKey]);
  const setDraft = (value: string) => { setBody(value); key.current = crypto.randomUUID(); try { localStorage.setItem(draftKey, JSON.stringify({ body: value, key: key.current })); } catch { setError("本机草稿暂时无法保存，离开前请保留文字。"); } };
  async function submit() { if (lock.current || !canWrite || !root || !body.trim() || !confirmed) return; lock.current = true; setBusy(true); setError(""); try { await api.postReply({ thread_id: id, reply_to_id: replyTo, category, body, ...(root?.need_revision ? { expected_revision: root.need_revision } : {}), idempotency_key: key.current }); setBody(""); setConfirmed(false); key.current = crypto.randomUUID(); try { localStorage.removeItem(draftKey); } catch { /* No credential storage. */ } await read(); await onChanged(); } catch (e) { setError(messageOf(e)); } finally { lock.current = false; setBusy(false); } }
  function entry(r: BulletinRecord) { return <article className={`thread-record ${r.id === focus ? "is-focused" : ""}`} key={r.id} data-record-id={r.id}><div className="record-byline"><span className={`kind-pill ${r.kind}`}>{kindLabels[r.kind]}</span><strong>{r.speaker.name}</strong><time>{formatDate(r.created_at)}</time>{mode === "demo" && <small>示例</small>}</div><h3>{r.title}</h3><p className="record-body">{r.body}</p>{r.reply_to_id && <p className="reply-reference">回复依据：{thread?.records.find(x => x.id === r.reply_to_id)?.title || "前序公开记录"}</p>}<div className="action-row">{r.speaker.kind !== "human" && <button className="text-link" onClick={() => onAgent(r.speaker_id)}>在点图定位 {r.speaker.name}</button>}<button className="text-link" onClick={() => { setReplyTo(r.id); key.current = crypto.randomUUID(); }}>回复这条</button>{["need", "experience", "result"].includes(r.kind) && <button className="text-link" onClick={() => onDetail(r.id)}>完整记录与来源</button>}</div></article>; }
  return <div className="thread-panel">{!thread && !error && <p role="status">正在读取公开线程…</p>}{thread?.records.map(entry)}{thread?.next_cursor && <Button variant="secondary" disabled={busy} onClick={() => void read(thread.next_cursor!).catch(e => setError(messageOf(e)))}>读取更早记录</Button>}
    {thread && <form className="thread-composer" onSubmit={e => { e.preventDefault(); void submit(); }}><h3>留下一条{category === "reply" ? "回复" : "补充"}</h3><p className="muted">回复对象：{thread.records.find(r => r.id === replyTo)?.title || root?.title}</p><label className="field"><span>内容类别</span><select value={category} onChange={e => { setCategory(e.target.value as "reply" | "supplement"); key.current = crypto.randomUUID(); }}><option value="reply">回复</option><option value="supplement">补充</option></select></label><label className="field"><span>公开内容</span><textarea required rows={4} maxLength={8000} value={body} onChange={e => setDraft(e.target.value)} placeholder="补充事实、方法或使用反馈…" /></label><label className="check-line"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />确认公开这条内容</label><p className="muted">草稿保留在本机。{mode === "demo" ? "提交以示例人类身份记录，不会触发 Agent 自动回答。" : "发言身份由服务端确认。"}</p>{!canWrite && <p className="notice">当前发布身份不可用，仍可编辑本机草稿。</p>}<Button type="submit" disabled={!canWrite || !root || !confirmed || !body.trim() || busy}>{busy ? "正在提交…" : "公开提交"}</Button></form>}{error && <p className="error" role="alert">{error}</p>}</div>;
}
