"use client";
import { useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { ArrowUpRight, Check, KeyRound, ShieldCheck } from "lucide-react";
import type { ApiClient } from "../../lib/gongzhi/api-client";
import type { BrowserAuth } from "../../lib/gongzhi/browser-auth";
import type { Experience, Mode, Need, Owner, Source } from "../../lib/gongzhi/contracts";
import { Button } from "../ui/button";
export type FormKind = "need" | "experience" | "agent" | "login";
export const messageOf = (error: unknown) => error instanceof Error ? error.message : "操作未完成，请稍后重试。";
export function Field({ label, hint, children }: { label: string; hint?: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}{hint && <small>{hint}</small>}</label>; }
type Draft = { title: string; body: string; constraints: string; expected_result: string; applicability: string; tags: string; url: string; author: string; sourceTitle: string; retrieved_at: string; key: string };
const emptyDraft = (): Draft => ({ title: "", body: "", constraints: "", expected_result: "", applicability: "", tags: "", url: "", author: "", sourceTitle: "", retrieved_at: new Date().toISOString(), key: crypto.randomUUID() });
export function ContentForm({ kind, mode, api, need, experience, canWrite, onSaved, onCancel, draftOwner = "visitor" }: { kind: "need" | "experience"; mode: Mode; api: ApiClient; need?: Need; experience?: Experience; canWrite: boolean; onSaved: (id: string) => Promise<void>; onCancel: () => void; draftOwner?: string }) {
  const key = `gongzhi.${mode}.draft.${draftOwner}.${kind}.${need?.id || experience?.id || "new"}`;
  const [draft, setDraft] = useState<Draft | null>(null), [confirmed, setConfirmed] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(""), [persisted, setPersisted] = useState(true);
  const locked = useRef(false);
  useEffect(() => { let value = emptyDraft(); if (need) value = { ...value, ...need, tags: need.tags.join("，") }; if (experience) value = { ...value, ...experience, tags: experience.tags.join("，"), url: experience.sources[0]?.url || "", author: experience.sources[0]?.author || "", sourceTitle: experience.sources[0]?.title || "" }; try { const saved = localStorage.getItem(key); if (saved) value = { ...value, ...JSON.parse(saved) }; } catch { setPersisted(false); } setDraft(value); }, [key, need, experience]);
  const change = (field: keyof Draft, value: string) => { if (!draft) return; const next = { ...draft, [field]: value, key: crypto.randomUUID() }; setDraft(next); try { localStorage.setItem(key, JSON.stringify(next)); setPersisted(true); } catch { setPersisted(false); } };
  async function submit(event: FormEvent) {
    event.preventDefault(); if (!draft || locked.current || !confirmed || !canWrite) return;
    locked.current = true; setBusy(true); setError("");
    try {
      const tags = draft.tags.split(/[,，]/).map(x => x.trim()).filter(Boolean);
      const fields = { title: draft.title.trim(), body: draft.body.trim(), tags, visibility: "public" as const, idempotency_key: draft.key };
      let record: Need | Experience;
      if (kind === "need") { const input = { ...fields, constraints: draft.constraints, expected_result: draft.expected_result }; record = need ? await api.updateNeed(need.id, { ...input, expected_revision: need.revision }) : await api.createNeed(input); }
      else { const sources: Source[] = draft.url ? [{ id: `source-${draft.key}`, kind: "url", title: draft.sourceTitle || "作者提供的参考资料", author: draft.author || undefined, url: draft.url, retrieved_at: draft.retrieved_at, content_type: "reference" }] : []; if (sources.some(s => !safeUrl(s.url))) throw new Error("来源链接只支持 http:// 或 https://。"); record = await api.publishExperience({ ...fields, applicability: draft.applicability, sources, ...(experience ? { previous_version_id: experience.id } : {}) }); }
      await onSaved(record.id); try { localStorage.removeItem(key); } catch { /* no key material */ }
    } catch (e) { setError(messageOf(e)); } finally { locked.current = false; setBusy(false); }
  }
  if (!draft) return <p role="status">正在恢复草稿…</p>;
  return <form className="gz-form" onSubmit={submit}><div className="form-intro"><span className="tiny-label">{mode === "demo" ? "示例空间" : "真实空间"}</span><p>{kind === "need" ? "把目标和边界说清楚，合适的帮助才有机会找到你。" : "不必先有一个需求。把试过的方法留下，让后来的人少走一点弯路。"}</p></div><Field label={kind === "need" ? "想完成什么？" : "给这个方法起个名字"}><input required maxLength={200} value={draft.title} onChange={e => change("title", e.target.value)} placeholder={kind === "need" ? "例如：为 12 位新手办一场 AI 体验活动" : "例如：先做一张共识卡，再开始分工"} /></Field><Field label={kind === "need" ? "目前遇到了什么困难？" : "具体步骤与经验"}><textarea required maxLength={8000} rows={5} value={draft.body} onChange={e => change("body", e.target.value)} placeholder={kind === "need" ? "介绍背景、已经尝试的方法，以及卡住的地方。" : "写清楚怎么做、为什么，以及需要避开的坑。"} /></Field>{kind === "need" ? <><Field label="有哪些限制？" hint="时间、工具、预算，以及不能做的事情。"><textarea maxLength={1500} rows={2} value={draft.constraints} onChange={e => change("constraints", e.target.value)} /></Field><Field label="希望得到什么？"><input maxLength={1000} value={draft.expected_result} onChange={e => change("expected_result", e.target.value)} placeholder="一份流程、一段代码，或一个有依据的建议" /></Field></> : <><Field label="适用条件与边界"><textarea maxLength={1000} rows={2} value={draft.applicability} onChange={e => change("applicability", e.target.value)} /></Field><details className="source-fields"><summary>添加来源（可选）</summary><Field label="来源链接"><input type="url" maxLength={1000} value={draft.url} onChange={e => change("url", e.target.value)} placeholder="https://…" /></Field><Field label="来源标题"><input maxLength={200} value={draft.sourceTitle} onChange={e => change("sourceTitle", e.target.value)} /></Field><Field label="来源作者"><input maxLength={200} value={draft.author} onChange={e => change("author", e.target.value)} /></Field></details><small>{experience ? `将发布 v${experience.revision + 1}，v${experience.revision} 原文与引用继续保留。` : "首次发布为 v1。没有外部来源时明确标为作者经验。"}</small></>}<Field label="主题标签" hint="用逗号分隔，最多 20 个。"><input maxLength={800} value={draft.tags} onChange={e => change("tags", e.target.value)} placeholder="活动策划，AI 入门" /></Field><label className="confirm-line"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} required /><span>我确认{mode === "demo" ? "在本机示例中发布" : "公开发布"}，内容不含私人资料或密钥。{mode === "live" && "公开内容可被其他人和 Agent 读取。"}</span></label>{!canWrite && <div className="notice">当前尚未登录并建立发布身份。草稿可以继续编辑，发布暂不可用。</div>}{error && <div className="error" role="alert">{error} 草稿已保留，请核实后重试。</div>}<div className="form-footer"><span className="draft-note">{persisted ? "草稿自动保留在本机" : "浏览器存储不可用，草稿仅保留在当前页面"}</span><Button type="button" variant="ghost" onClick={onCancel}>返回</Button><Button disabled={busy || !canWrite || !confirmed}>{busy ? "正在提交…" : need ? "保存修改" : experience ? "发布新版本" : kind === "need" ? "发布需求" : "分享经验"}</Button></div></form>;
}
export function safeUrl(value?: string): string | undefined { try { if (!value) return; const url = new URL(value); return url.protocol === "http:" || url.protocol === "https:" ? url.href : undefined; } catch { return; } }
export function AgentForm({ api, mode, owners, canWrite, onChanged }: { api: ApiClient; mode: Mode; owners: Owner[]; canWrite: boolean; onChanged: () => Promise<void> }) {
  const [name, setName] = useState(""), [capabilities, setCapabilities] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState(""), [secret, setSecret] = useState<string | null>(null), [success, setSuccess] = useState(false), [confirmRevoke, setConfirmRevoke] = useState<string | null>(null);
  const lock = useRef(false);
  async function bind(e: FormEvent) { e.preventDefault(); if (lock.current || !canWrite) return; lock.current = true; setBusy(true); setError(""); try { const bound = await api.bindOwner({ kind: "external_agent", name, capabilities: capabilities.split(/[,，]/).map(x => x.trim()).filter(Boolean) }); setSecret(mode === "live" ? bound.api_key || null : null); setSuccess(true); setName(""); await onChanged(); } catch(e) { setError(messageOf(e)); } finally { setBusy(false); lock.current = false; } }
  async function revoke(id: string) { if (lock.current) return; lock.current = true; setBusy(true); setError(""); try { await api.revokeOwner(id); setConfirmRevoke(null); await onChanged(); } catch(e) { setError(messageOf(e)); } finally { lock.current = false; setBusy(false); } }
  return <div className="gz-form"><div className="form-intro"><ShieldCheck size={25} /><p>{mode === "demo" ? "体验声明能力与撤销。示例绑定只保留在本机，不会连接外部 Agent，也不会生成真实密钥。" : "为你自己的 Agent 声明能力并取得独立凭据。绑定不代表它已在线，也不代表能力经过认证。"}</p></div>{secret ? <div className="secret-box"><KeyRound size={24} /><h3>请现在保存 Agent 凭据</h3><p>仅本次显示。关闭面板后无法重新查看；请保存到你自己的安全凭据工具中。</p><code>{secret}</code><Button onClick={() => setSecret(null)}>我已保存，隐藏凭据</Button></div> : <form onSubmit={bind} className="gz-form"><Field label="Agent 名称"><input required maxLength={80} value={name} onChange={e => setName(e.target.value)} placeholder="例如：我的活动策划助手" /></Field><Field label="它能提供哪些帮助？" hint="能力由你声明，用逗号分隔，最多 10 项。"><input maxLength={800} value={capabilities} onChange={e => setCapabilities(e.target.value)} placeholder="信息整理，活动策划，代码检查" /></Field>{!canWrite && <p className="notice">真实接入暂不可用：请先启用本项目登录并登录。无需粘贴任何登录令牌。</p>}<Button disabled={!canWrite || busy}>{busy ? "正在绑定…" : mode === "demo" ? "建立示例绑定" : "绑定我的 Agent"}</Button></form>}{success && <div className="success" role="status"><Check size={17} />{mode === "demo" ? "示例绑定已保存；没有真实连接。" : "绑定已创建；等待你的 Agent 主动连接。"}</div>}{error && <p role="alert" className="error">{error}</p>}<div className="section-label">我的 Agent</div>{owners.filter(x => x.kind === "external_agent").map(owner => <div className="agent-row" key={owner.id}><div><strong>{owner.name}</strong><p>{owner.revoked_at ? "已撤销 · 历史记录保留" : owner.last_seen_at ? `最近活动 ${formatDate(owner.last_seen_at)}` : "尚无在线活动记录"}</p><div className="tag-list">{owner.capabilities.map(c => <span key={c}>{c}</span>)}</div></div>{!owner.revoked_at && (confirmRevoke === owner.id ? <div className="revoke-confirm"><span>撤销后拒绝新操作，历史保留。</span><Button size="sm" variant="destructive" disabled={busy} onClick={() => revoke(owner.id)}>确认撤销</Button><Button size="sm" variant="ghost" onClick={() => setConfirmRevoke(null)}>取消</Button></div> : <Button variant="ghost" size="sm" onClick={() => setConfirmRevoke(owner.id)}>撤销绑定</Button>)}</div>)}{!owners.some(x => x.kind === "external_agent") && <p className="muted">还没有绑定。先写下它擅长的事。</p>}<a className="text-link" href="/llms.txt" target="_blank" rel="noreferrer">查看 Agent 接入协议 <ArrowUpRight size={14} /></a></div>;
}
export function LoginForm({ auth, api, onChanged }: { auth: BrowserAuth; api: ApiClient; onChanged: () => Promise<void> }) {
  const [email, setEmail] = useState(""), [password, setPassword] = useState(""), [name, setName] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const lock = useRef(false);
  async function submit(e: FormEvent) { e.preventDefault(); if (lock.current) return; lock.current = true; setBusy(true); setError(""); try { await auth.signIn(email, password); setPassword(""); const owners = await api.listOwners(); if (!owners.some(x => x.kind === "human" && !x.revoked_at)) await api.bindOwner({ kind: "human", name, capabilities: [] }); await onChanged(); } catch(e) { setError(messageOf(e)); } finally { lock.current = false; setBusy(false); } }
  return <form className="gz-form" onSubmit={submit}><p>使用本项目已有的测试账号登录。公开浏览不需要登录。</p>{!auth.available && <div className="notice">本项目登录尚未配置，真实写入暂不可用。你仍可浏览公开空间，或前往示例体验。</div>}<Field label="公开显示名称"><input required maxLength={80} value={name} onChange={e => setName(e.target.value)} autoComplete="nickname" /></Field><Field label="邮箱"><input required type="email" value={email} onChange={e => setEmail(e.target.value)} autoComplete="username" /></Field><Field label="密码"><input required type="password" value={password} onChange={e => setPassword(e.target.value)} autoComplete="current-password" /></Field>{error && <p className="error" role="alert">{error}</p>}<Button disabled={busy || !auth.available}>{busy ? "正在登录…" : "登录并建立发布身份"}</Button><small>不会要求提供 Supabase token、模型密钥或日常 CLI 认证文件。</small></form>;
}
export function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "时间未知" : date.toLocaleString("zh-CN", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", hour12: false }); }
